### ISSUE TITLE
approxQuantile works in DLT debug, but does not work within the databricks website itself. 

### ISSUE THREAD

**Issue by Trodenn** [souvik-databricks/dlt-with-debug#8]
Hi, 

First of all, please do allow me to thank you greatly for this package, it is very convenient to be able to debug the code meant to create a pipeline of delta live table without having the run the entire thing. However I am currently experiencing some problems that I find hard to resolve. 

To give more context, please check the code below: 

```
@dlt.table(name = "customer_order_silver_v2")
def capping_unitPrice_Qt():
    df =  dlt.read("customer_order_silver")
    boundary_unit = [0,0]
    boundary_qty = [0,0]
    boundary_unit = df.select(col("UnitPrice")).approxQuantile('UnitPrice',[0.05,0.95], 0.25)

    boundary_qty = df.select(col("Quantity")).approxQuantile('Quantity',[0.05,0.95], 0.25)
    print(boundary_unit)
    print(boundary_unit[0])
    print(boundary_unit[1])
    

    df = df.withColumn('UnitPrice', F.when(col('UnitPrice') > boundary_unit[1], boundary_unit[1])
                                       .when(col('UnitPrice') < boundary_unit[0], boundary_unit[0])
                                       .otherwise(col('UnitPrice')))
    
    df = df.withColumn('Quantity', F.when(col('Quantity') > boundary_qty[1], boundary_qty[1])
                                       .when(col('Quantity') < boundary_qty[0], boundary_qty[0])
                                       .otherwise(col('Quantity')))
                                          
    return df
```
 When I run this the code for this DLT, the approxQuantile() in it seems to be not working. What I get after running this: 
![image](https://user-images.githubusercontent.com/48042375/215511777-b8c9ce92-ea5d-4364-bc71-19a4e409ac6a.png)

Yet somehow, after I use the debug package and rewrite the code into: 

```
#this way of writing might be too complex. An alternative solution is to write the DLT as a general function and then pass it as a function. 
@dlt.create_table(name = "customer_order_silver_v2")
@dltwithdebug(globals())
# @dlt.table(name = "customer_order_silver_v2")
def capping_unitPrice_Qt():
    df =  dlt.read("wtchk_customer_order_filtered")


    boundary_unit = [0,0]
    boundary_qty = [0,0]
    boundary_unit = df.select(col("UnitPrice")).approxQuantile('UnitPrice',[0.05,0.95], 0.25)
 

    boundary_qty = df.select(col("Quantity")).approxQuantile('Quantity',[0.05,0.95], 0.25)
    print(boundary_unit)
    print(boundary_unit[0])
    print(boundary_unit[1])
    



    df = df.withColumn('UnitPrice', F.when(col('UnitPrice') > boundary_unit[1], boundary_unit[1])
                                       .when(col('UnitPrice') < boundary_unit[0], boundary_unit[0])
                                       .otherwise(col('UnitPrice')))
    
    df = df.withColumn('Quantity', F.when(col('Quantity') > boundary_qty[1], boundary_qty[1])
                                       .when(col('Quantity') < boundary_qty[0], boundary_qty[0])
                                       .otherwise(col('Quantity')))
                                          
    return df

showoutput(capping_unitPrice_Qt)
```
The code runs and it produces the table. as well as the value that I need: 
![image](https://user-images.githubusercontent.com/48042375/215512307-b1ee9441-9c1b-49dc-be50-e1482458a2a5.png)
I really cannot wrap my head around as what is not well written. I would appreciate any kind of input or advice. Thank you very much!

**Comment by souvik-databricks** [comment]
Hi @Trodenn Thank you for using dlt-with-debug! 

I think getting in touch with your company's Databricks contact person and then raising a databricks support ticket citing the behaviour difference would be better.

**Comment by Trodenn** [comment]
Ok, I will see how it goes with the ticket. But before I wanted to confirm something else. Aside from the issue that I am encountering technically speaking whatever that works with the debug package, should work in the databricks delta live table right? Also is there a specific reason why when I am testing the debugged code on the databricks' delta live table I have to change the function names ? is there a way to make it work on databricks without having to make the change everytime?

**Comment by souvik-databricks** [comment]
- Yes whatever works in dlt-with-debug should be working in Databricks DLT Environment also.

- You don't have to change you can use `dlt.create_table()` in both dlt-with-debug and databricks dlt.

**Comment by Trodenn** [comment]
how about the function names? if I use "dlt.read("table_name")" it somehow does not work in the debug, and I have to put the function name. When switching back to DB DLT, I have to change it back to the table name (by table name I mean the one defined by the "name" parameter when summoning dlt.create_table or dlt.table)

**Comment by souvik-databricks** [comment]
Ahh okay got it. Yeah that's a code implementation that I have to do. I am not getting the free time to get that implemented.

Will try to address it in between Feb 6 - 10

**Comment by Trodenn** [comment]
I see, thanks for replying all my questions this fast! I really appreciate it. And yeah I think that feature would be great addition to this package!
